---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Weather


components: 
  schemas: 
    WeatherObserved: 
      $ref: "https://smart-data-models.github.io/dataModel.Weather/WeatherObserved/model.yaml#/WeatherObserved"
    PressureTendency: 
       $ref: "https://smart-data-models.github.io/dataModel.Weather/WeatherObserved/model.yaml#/PressureTendency"
    WeatherVisibility:
      $ref: 'https://smart-data-models.github.io/dataModel.Weather/weather-model.yaml#/Visibility'
    WeatherType:
      $ref: 'https://smart-data-models.github.io/dataModel.Weather/weather-model.yaml#/WeatherType'
info: 
  description: |
    An observation of weather conditions at a certain place and time. This data
    model has been developed in cooperation with mobile operators and the
    [GSMA](https://www.gsma.com/iot/iot-big-data/).
  title: WeatherObserved
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - WeatherObserved
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Weather/WeatherObserved/examples/example.jsonld"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Weather/WeatherObserved/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
